name: build image
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: fetch armbian/build
      uses: actions/checkout@v3
      with:
        repository: armbian/build
        fetch-depth: 0

    - name: checkout
      uses: actions/checkout@v3
      with:
        path: userpatches

    - name: build armbian image
      id: compile
      run: |
        pwd
        git checkout $(awk -F '\"' '/LIB_TAG/ {print $2}' userpatches/config-phicomm-n1.conf)
        bash compile.sh
